spring.application.name=courseqa-springboot-mvc2-skeleton
server.port=8080

# SQL Server configuration
# Change username/password according to your local SQL Server.
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=VietnameseCourseQA20DB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=YourStrongPassword123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Use SQL script in /database, do not auto-create tables
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# File upload
app.upload-dir=uploads

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
